# Extra arguments for logbookd

# -r : reduced write mode
# -d : database path
# -g : amount of uncommitted data (kB) before flushing to disk
#
# Default:
#   -r -g 8192 -d /var/log/logbookd.db

LOGBOOKD_OPTS="-r -g 8192 -d /var/log/logbookd.db"
