# voidlinux remote repositories (glibc)
repository=https://repo-default.voidlinux.org/current/bootstrap
repository=https://repo-default.voidlinux.org/current
repository=https://repo-default.voidlinux.org/current/nonfree
repository=https://repo-default.voidlinux.org/current/debug

# lazylinux remote repositories (glibc)
repository=https://github.com/lazylinuxos/lazy-repo/releases/latest/download